### ISSUE TITLE
Product creation step for 1000+ products

### ISSUE THREAD

**Issue by edudemy** [Instamojo/Instamojo-Magento#7]
Hello Instamojo Team,

As per documentation, the first (or any? if already 1000 products are created) product has to be created in instamojo dashboard. IS this to be repeated for 1000+ products or only for the first product created. The normal workflow for payment integration is only to add the API key, salt. There are additional "product creation and custom fields" involved for instamojo . Hence this query. Could you please clarify.

Thank You

Ref:
Product creation ...
"After the custom field has been created Existing Custom Fields section will appear. Copy the name shown under Field ID column, its format is Field_xxxx, where xxxx are some numbers(Note that this is case sensitive!). In this example the value is Field_6473."

**Comment by ashwch** [comment]
You have to only create one product(with custom field) and use its URL in plugin's settings.
