### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by kaushik1101** [Instamojo/Instamojo-Magento#8]
Got this following error while trying to install extension using magento connect manager. 

CONNECT ERROR: Package community/Instamojo_Imojo 0.1.9: requires PHP version >= 5.2.0 and <= 5.6.28 current is: 5.6.30

**Comment by ashwch** [comment]
Thanks for pointing this out, we will update this by tomorrow EOD.

**Comment by kaushik1101** [comment]
Any update?

**Comment by ashwch** [comment]
@kaushik1101 The [latest release(0.1.11)](https://www.magentocommerce.com/magento-connect/instamojo-payment-gateway.html) has fixed this issue. Apologies for the delay.
